# docker-compose -f data-playground.yml up -d
version: "3.4"
services:

  adventure-works-db:
    image: stvansolano/adventure-works:latest
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis:
    image: redis:4.0.8-alpine
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: ingress
    volumes:
      - "~/data/${STACK_NAME}/redis:/data"

  code-server:
    image: stvansolano/code-server:latest
    ports:
      - "8080:8080"
      - "8443:8443"

    volumes:
      - "$PWD/:/home/playground"
      
  dotnet-sql-server:
    build:
      context: .
      dockerfile: samples/dotnet-sql-server/Dockerfile
    ports:
    - "5001:80"  
    environment:
      -  ASPNETCORE_URLS=http://+:80
    command: |
      - echo "ASP.NET Backend up and running!"
    links:
    - adventure-works-db
    depends_on:
    - adventure-works-db

    # attach shell
    # docker ps
    # docker exec -it [container-id] bash
    # cat ~/.config/code-server/config.yaml