# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dotnet-backend:
    image: dotnet-backend
    build:
      context: .
      dockerfile: samples/dotnet-backend/Dockerfile
    ports:
      - 5000
      - 5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
